name: Production Build

concurrency:
  group: production-build-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review, review_requested]

jobs:
  # We are going to build an image specifically for testing and push it to ghcr.io (GitHub Container Registry)
  # This image is used throughout the entire github workflow until it is built for final deployment
  build-test-image:
    name: Build Image for Testing
    runs-on: ubuntu-latest

    permissions:
      packages: write # Needed to push docker image to ghcr.io
      contents: read # Needed to read code in repository

    steps:
      # Docker buildx is useful for caching images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:test-production
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:cache-production-test
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:cache-production-test,mode=max
          target: build # This is the target stage in the Dockerfile

          labels: |
            org.opencontainers.image.title=Test Image
            org.opencontainers.image.description=Image used for testing
            org.opencontainers.image.source=ghcr.io/${{ github.repository }}

  # We are going to build an image specifically for final deployment and push it to ghcr.io (GitHub Container Registry)
  build-final-image:
    name: Build Image for Deployment (Production)
    runs-on: ubuntu-latest
    needs: [build-test-image]

    permissions:
      packages: write # Needed to push docker image to ghcr.io
      contents: read # Needed to read code in repository

    steps:
      # Docker buildx is useful for caching images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:latest,mode=max
          target: release # This is the target stage in the Dockerfile
          labels: |
            org.opencontainers.image.title=Production Image
            org.opencontainers.image.description=Image used for production deployment
            org.opencontainers.image.source=ghcr.io/${{ github.repository }}

  clean-old-images:
    name: Clean Old Images
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 24
          delete-only-untagged-versions: true
